name: Terraform

on:
    push:
        branches:
            - '**'
    pull_request:
    workflow_dispatch:


permissions:
    id-token: write
    contents: read

jobs:
    terraform:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v1

            - name: "Terraform Format"
              id: fmt
              run: terraform fmt

            - name: "Terraform Init"
              id: init
              run: terraform init

            - name: "Terraform Validate"
              id: validate
              run: terraform validate -no-color

            - name: Terraform Plan
              id: plan
              env:
                  TF_VAR_subscription_id: ${{ secrets.SUBSCRIPTION_ID }}
                  TF_VAR_postgresql_server_name: ${{ secrets.POSTGRESQL_SERVER_NAME }}
                  TF_VAR_admin_username: ${{ secrets.ADMIN_USERNAME }}
                  TF_VAR_admin_password: ${{ secrets.ADMIN_PASSWORD }}
                  TF_VAR_database_name: ${{ secrets.DATABASE_NAME }}
                  TF_VAR_agent_client_id: ${{ secrets.AZURE_CLIENT_ID }}
                  TF_VAR_agent_client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}
                  TF_VAR_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
              run: terraform plan -out tfplan

            - name: Stash Terraform Plan Output
              uses: actions/upload-artifact@v3
              with:
                  name: tfplan
                  path: tfplan

    apply:
        if: github.ref == 'refs/heads/main'
        runs-on: ubuntu-latest
        needs: terraform

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v1

            - name: Azure Login
              uses: azure/login@v1
              with:
                  creds: ${{ secrets.AZURE_CREDENTIALS }}

            - name: Download Terraform Plan Output
              uses: actions/download-artifact@v2
              with:
                  name: tfplan

            - name: Terraform Apply
              env:
                  TF_VAR_subscription_id: ${{ secrets.SUBSCRIPTION_ID }}
                  TF_VAR_postgresql_server_name: ${{ secrets.POSTGRESQL_SERVER_NAME }}
                  TF_VAR_admin_username: ${{ secrets.ADMIN_USERNAME }}
                  TF_VAR_admin_password: ${{ secrets.ADMIN_PASSWORD }}
                  TF_VAR_database_name: ${{ secrets.DATABASE_NAME }}
                  TF_VAR_agent_client_id: ${{ secrets.AZURE_CLIENT_ID }}
                  TF_VAR_agent_client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}
                  TF_VAR_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
              run: terraform apply -auto-approve tfplan